spring.application.name=demo
server.port=8082
spring.datasource.url=jdbc:mysql://host.docker.internal:3399/demo_db
spring.datasource.username=root
spring.datasource.password=PharmTwo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect